charts:
  - {glob: '**/value*.png', type: file}
  - yDomain: [0, 1]
    yKey: success_rate/mean
    xKey: epoch
  - yDomain: [0, 51]
    yKey: episode_len/mean
    xKey: epoch
keys:
  - run.status
  - Args.env_id
  - DEBUG.ground_truth_neighbor_r
  - DEBUG.supervised_value_fn
  - Args.lr
  - Args.binary_reward
  - DEBUG.real_r_distance
  - {metrics: success_rate/mean}
