charts:
  - {xKey: epoch, yKey: accuracy/mean, yDomain: [0.8, 1]}
  - {xKey: epoch, yKey: accuracy/1/mean, yDomain: [0.8, 1]}
  - {xKey: epoch, yKey: accuracy/2/mean, yDomain: [0.8, 1]}
keys:
  - run.status
  - Args.lr
  - Args.seed
  - {metrics: accuracy/mean}
